[package]
name = "youram"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
reda-lib = "0.4.0"
reda-sp = "0.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
tracing = "0.1.41"
