[package]
name = "youram-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
regex = "1.11.1"
convert_case = "0.8.0"